export const LOCAL_SERVER_OPTION = { name: 'Local', address: '' };

export const REQUIRED_ELEMENT_IDS = [
  'themeToggle',
  'themeIcon',
  'connectionStatus',
  'connectionText',
  'alertsPanel',
  'exportOverlay',
  'exportPanel',
  'exportCSV',
  'exportJSON',
  'exportClose',
  'exportTrigger',
  'serverSwitcher',
  'filterFrom',
  'filterTo',
  'applyFilter',
  'clearFilter',
  'initialLoading',
  'systemChart',
  'networkChart',
  'usageDonut',
  'heartbeatList',
  'heartbeatSearch',
  'heartbeatSummary',
  'cpu',
  'memory',
  'networkRx',
  'networkTx',
  'loadAvg',
  'cpuBar',
  'memoryBar',
  'cpuTrend',
  'memoryTrend',
  'loadTrend'
];
