export const state = {
  systemChart: null,
  networkChart: null,
  usageDonut: null,
  refreshInterval: 2000,
  refreshTimer: null,
  previousMetrics: null,
  serverConfig: null,
  availableServers: [],
  selectedServer: null,
  selectedBaseUrl: '',
  pendingFilter: null,
  historicalSeries: [],
  historicalMode: false,
  filterElements: null,
  connectionState: 'online',
  currentTheme: 'dark',
  activeAlerts: new Map(),
  notificationPermission: 'default',
  lastMetricValues: {},
  thresholds: {
    cpu: { warning: 70, critical: 90 },
    memory: { warning: 80, critical: 95 },
    disk: { warning: 85, critical: 95 }
  },
  isLoading: false,
  retryCount: 0,
  maxRetries: 3,
  filteredHeartbeats: [],
  searchTerm: '',
  isInitialLoad: true,
  chartUpdateQueue: [],
  isUpdatingCharts: false,
  initialized: false,
  initInProgress: false,
  bootstrapIntervalId: null,
  watchersRegistered: false,
  eventsRegistered: false,
  lifecycleRegistered: false
};
